### ISSUE TITLE
PyLTEs as a module

### ISSUE THREAD

**Issue by mariuszslabicki** [iitis/PyLTEs#3]
Improve code to be able to use PyLTEs as a module (and just "import PyLTEs")

**Comment by cumhurtorun** [comment]
Hello,
Can I test the queue management algorithms with Pylte?

**Comment by mariuszslabicki** [comment]
Hi,
It depends in which network element you want to test.

**Comment by cumhurtorun** [comment]
Queue management algorithms in the enodeb, such as droptail, red vs.

**Comment by mariuszslabicki** [comment]
I am afraid you can't evaluate them in the PyLTEs. Probably a better way for that will be the OMNeT++.
